FROM golang:1.25.4-alpine3.22 AS builder

ARG WORKDIR_PATH
WORKDIR ${WORKDIR_PATH}

RUN apk --no-cache add curl
RUN go install github.com/air-verse/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY ./src ./src
COPY go.* .
COPY  .air.toml .

RUN go mod download

CMD ["air"]
