# BUILD STAGE
FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.* .
RUN go mod download

COPY ./src ./src

RUN go build -o main ./src/main.go

# RUN STAGE
FROM alpine
WORKDIR /app

COPY --from=builder /app/main .

ENV PORT=3000
EXPOSE ${PORT}

CMD ["./main"]
