# BUILD STAGE
FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.* .
RUN go mod download

COPY ./src ./src

RUN go build -o bin ./src/cmd

# RUN STAGE
FROM alpine
WORKDIR /app

COPY --from=builder /app/bin .

ENV PORT=3000
EXPOSE ${PORT}

CMD ["./bin"]
